itemFeatureDim: 18  # contains an integer denoting the dimensionality of the items
latent_dim: 3  # contains an integer denoting the latent dimension of the items

lambda_ : 1  # contains a real number for lambda parameter

alpha: 0.375  # 0.5 for CoLin's single alpha, for the first term in the variance in UCB in FactorUCB
alpha2: 0.375  # alpha2 parameter in FactorUCB, for the second term in the variance in UCB

path_input: "data/MovieLens/1M"  # complete address of datasets

run_CF: True  # If we need to run CF from scratch or use the existing weights file
run_Kmeans: True

# these won't be read unless skip below is not greater than zero
warmStart_input: # a dictionary of two things: userTheta for the path to warm starting userTheta matrix, AInv similarly
  userTheta: "/"
  AInv_in: False
  AInv: "/"
  Latents_in: False
  V: "/"
  CInv: "/"

#clusterNum: 100  # number of clusters
#sparsity: 50  # the Level of sparsity, default is the number of clusters clusterNum
#top_users: 200  # default is all the users, select top_users with the most ratings
#top_movies: 50  # default is 50, select top n most rated movies among top_users with the most ratings
#embeddingSize: 50  # default is 50, size of the embedding for CF

#stopAfter: 10000  # default 10000
recordEvery: 250  # default 100
#skip: 0  # default 0
#batchUpdates: 1  # default 1
#initBanditParams: 'zeros'  # default 'zeros'