itemFeatureDim: 18  # contains an integer denoting the dimensionality of the items
latent_dim: 3  # contains an integer denoting the latent dimension of the items

lambda_ : 1  # contains a real number for lambda parameter

alpha: 0.5  # for CoLin's single alpha
alpha1: 0.375  # contains a real number for alpha parameter in FactorUCB, for the first term in the variance in UCB
alpha2: 0.375  # contains a real number for alphaz parameter in FactorUCB, for the second term in the variance in UCB

path_input: "/data/MovieLens/1M"  # complete address of datasets

# complete address of where to store CTR values, as well as userTheta and AInv for warm start purposes
path output: "/results"

# these won't be read unless skip below is not greater than zero
warmStart_input: # a dictionary of two things: userTheta for the path to warm starting userTheta matrix, AInv similarly
  userTheta: "/"
  AInv_in: False
  AInv: "/"
  Latents_in: False
  V: "/"
  CInv: "/"

#clusterNum: 100  # number of clusters
#sparsity: 50  # the Level of sparsity
#top_users: 200  # default is 10000000, select top_users with the most ratings
#n: 50  # default is 50, select top n most rated movies among top_users with the most ratings
#embeddingSize: 50  # default is 50, size of the embedding for CF

#stopAfter: 10000  # default 10000
#recordEvery: 1000  # default 1000
skip: 0  # default 0
#batchUpdates: 1  # default 1
#initializeBanditParams: 'zeros'  # default 'zeros'